In [26]:
import pandas as pd
import requests

In [27]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated"

params = {
    "api_key": "fab93650a0ae7fa86f4baa9e0796a145",
    "language": "en-US",
    "page": 1
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.json())

200
{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg', 'genre_ids': [12, 16, 10751, 14], 'id': 1007757, 'title': 'Swapped', 'original_language': 'en', 'original_title': 'Swapped', 'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.', 'popularity': 184.1031, 'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg', 'release_date': '2026-05-01', 'softcore': False, 'video': False, 'vote_average': 9.0, 'vote_count': 1656}, {'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'title': 'The Shawshank Redemption', 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 90.5775, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'softcore': False, 'video': False, 'vote_average': 8.722, 'vote_count': 30538}, {'adult': False, 'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg', 'genre_ids': [18, 80], 'id': 238, 'title': 'The Godfather', 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 44.29, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'softcore': False, 'video': False, 'vote_average': 8.688, 'vote_count': 23019}, {'adult': False, 'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg', 'genre_ids': [878, 12], 'id': 687163, 'title': 'Project Hail Mary', 'original_language': 'en', 'original_title': 'Project Hail Mary', 'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.', 'popularity': 188.8313, 'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg', 'release_date': '2026-03-15', 'softcore': False, 'video': False, 'vote_average': 8.7, 'vote_count': 4929}, {'adult': False, 'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 'genre_ids': [18, 80], 'id': 240, 'title': 'The Godfather Part II', 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 30.5158, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'softcore': False, 'video': False, 'vote_average': 8.572, 'vote_count': 13958}, {'adult': False, 'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg', 'genre_ids': [18, 9648], 'id': 1330021, 'title': 'Remarkably Bright Creatures', 'original_language': 'en', 'original_title': 'Remarkably Bright Creatures', 'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.', 'popularity': 38.644, 'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg', 'release_date': '2026-05-07', 'softcore': False, 'video': False, 'vote_average': 8.572, 'vote_count': 598}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'title': "Schindler's List", 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 26.048, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'softcore': False, 'video': False, 'vote_average': 8.569, 'vote_count': 17506}, {'adult': False, 'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg', 'genre_ids': [18], 'id': 389, 'title': '12 Angry Men', 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 23.5013, 'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg', 'release_date': '1957-04-10', 'softcore': False, 'video': False, 'vote_average': 8.6, 'vote_count': 10029}, {'adult': False, 'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'title': 'Spirited Away', 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 32.6243, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'softcore': False, 'video': False, 'vote_average': 8.535, 'vote_count': 18392}, {'adult': False, 'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg', 'genre_ids': [28, 80, 53], 'id': 155, 'title': 'The Dark Knight', 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 41.699, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'softcore': False, 'video': False, 'vote_average': 8.531, 'vote_count': 35877}, {'adult': False, 'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'title': 'Dilwale Dulhania Le Jayenge', 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 17.1904, 'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg', 'release_date': '1995-10-20', 'softcore': False, 'video': False, 'vote_average': 8.513, 'vote_count': 4593}, {'adult': False, 'backdrop_path': '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg', 'genre_ids': [10402, 18], 'id': 936075, 'title': 'Michael', 'original_language': 'en', 'original_title': 'Michael', 'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.', 'popularity': 382.8024, 'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg', 'release_date': '2026-04-22', 'softcore': False, 'video': False, 'vote_average': 8.51, 'vote_count': 1916}, {'adult': False, 'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'title': 'The Green Mile', 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 27.2486, 'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', 'release_date': '1999-12-10', 'softcore': False, 'video': False, 'vote_average': 8.507, 'vote_count': 19313}, {'adult': False, 'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'title': 'The Lord of the Rings: The Return of the King', 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 45.3962, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'softcore': False, 'video': False, 'vote_average': 8.499, 'vote_count': 26628}, {'adult': False, 'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'title': 'Parasite', 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 36.4975, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'softcore': False, 'video': False, 'vote_average': 8.494, 'vote_count': 20712}, {'adult': False, 'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg', 'genre_ids': [35, 10749], 'id': 1181678, 'title': '¿Quieres ser mi hijo?', 'original_language': 'en', 'original_title': '¿Quieres ser mi hijo?', 'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.', 'popularity': 10.2466, 'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg', 'release_date': '2023-09-21', 'softcore': False, 'video': False, 'vote_average': 8.5, 'vote_count': 354}, {'adult': False, 'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 'genre_ids': [53, 80, 35], 'id': 680, 'title': 'Pulp Fiction', 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 31.8224, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'softcore': False, 'video': False, 'vote_average': 8.483, 'vote_count': 30264}, {'adult': False, 'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'title': 'Your Name.', 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 28.1092, 'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg', 'release_date': '2016-08-26', 'softcore': False, 'video': False, 'vote_average': 8.481, 'vote_count': 12606}, {'adult': False, 'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'title': 'Interstellar', 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 70.5674, 'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg', 'release_date': '2014-11-05', 'softcore': False, 'video': False, 'vote_average': 8.478, 'vote_count': 39986}, {'adult': False, 'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', 'genre_ids': [37], 'id': 429, 'title': 'The Good, the Bad and the Ugly', 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 25.403, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-23', 'softcore': False, 'video': False, 'vote_average': 8.5, 'vote_count': 9676}], 'total_pages': 546, 'total_results': 10915}

In [28]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",184.1031,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,9.000,1656
1,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,90.5775,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.722,30538

In [29]:
df = pd.DataFrame(response.json()['results'])[['id','title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,184.1031,9.000,1656
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,90.5775,8.722,30538
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,44.2900,8.688,23019
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,188.8313,8.700,4929
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,30.5158,8.572,13958
5,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,38.6440,8.572,598
6,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.0480,8.569,17506
7,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.5013,8.600,10029
8,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,32.6243,8.535,18392
9,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,41.6990,8.531,35877
10,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,17.1904,8.513,4593
11,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,382.8024,8.510,1916
12,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,27.2486,8.507,19313
13,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,45.3962,8.499,26628
14,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,36.4975,8.494,20712
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,10.2466,8.500,354
16,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,31.8224,8.483,30264
17,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,28.1092,8.481,12606
18,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,70.5674,8.478,39986
19,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,25.4030,8.500,9676

In [30]:
df.shape

(20, 7)

In [8]:
import pandas as pd
import requests

dfs = []

for i in range(1, 20):
    url = "https://api.themoviedb.org/3/movie/top_rated"

    params = {
        "api_key": "fab93650a0ae7fa86f4baa9e0796a145",
        "language": "en-US",
        "page": i
    }

    while True:
        try:
            response = requests.get(url, params=params)
            break
        except:
            print(f"Retrying page {i}...")

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date',
         'popularity', 'vote_average', 'vote_count']
    ]

    dfs.append(temp_df)

df = pd.concat(dfs, ignore_index=True)

Retrying page 1...
Retrying page 1...
Retrying page 1...
Retrying page 2...
Retrying page 3...
Retrying page 6...
Retrying page 8...
Retrying page 9...
Retrying page 9...
Retrying page 9...
Retrying page 10...
Retrying page 10...
Retrying page 10...
Retrying page 10...
Retrying page 10...
Retrying page 12...
Retrying page 15...
Retrying page 17...
Retrying page 18...
Retrying page 18...
Retrying page 18...
Retrying page 18...
Retrying page 18...
Retrying page 19...
Retrying page 19...
Retrying page 19...
Retrying page 19...

In [5]:
dfs

[         id                                          title  \
 0   1007757                                        Swapped
 1       278                       The Shawshank Redemption
 2       238                                  The Godfather
 3    687163                              Project Hail Mary
 4       240                          The Godfather Part II
 5   1330021                    Remarkably Bright Creatures
 6       424                               Schindler's List
 7       389                                   12 Angry Men
 8       129                                  Spirited Away
 9       155                                The Dark Knight
 10    19404                    Dilwale Dulhania Le Jayenge
 11   936075                                        Michael
 12      497                                 The Green Mile
 13      122  The Lord of the Rings: The Return of the King
 14   496243                                       Parasite
 15  1181678                          ¿Quieres ser mi hijo?
 16      680                                   Pulp Fiction
 17   372058                                     Your Name.
 18   157336                                   Interstellar
 19      429                 The Good, the Bad and the Ugly

                                              overview release_date  \
 0   A small woodland creature and a majestic bird,...   2026-05-01
 1   Imprisoned in the 1940s for the double murder ...   1994-09-23
 2   Spanning the years 1945 to 1955, a chronicle o...   1972-03-14
 3   Science teacher Ryland Grace wakes up on a spa...   2026-03-15
 4   In the continuing saga of the Corleone crime f...   1974-12-20
 5   Through unlikely bonds formed during night shi...   2026-05-07
 6   The true story of how businessman Oskar Schind...   1993-12-15
 7   The defense and the prosecution have rested an...   1957-04-10
 8   A young girl, Chihiro, becomes trapped in a st...   2001-07-20
 9   Batman raises the stakes in his war on crime. ...   2008-07-16
 10  Raj is a rich, carefree, happy-go-lucky second...   1995-10-20
 11  The story of Michael Jackson, one of the most ...   2026-04-22
 12  A supernatural tale set on death row in a Sout...   1999-12-10
 13  As armies mass for a final battle that will de...   2003-12-17
 14  All unemployed, Ki-taek's family takes peculia...   2019-05-30
 15  Lu, a conformist woman in her forties, learns ...   2023-09-21
 16  A burger-loving hit man, his philosophical par...   1994-09-10
 17  High schoolers Mitsuha and Taki are complete s...   2016-08-26
 18  The adventures of a group of explorers who mak...   2014-11-05
 19  While the Civil War rages on between the Union...   1966-12-23

     popularity  vote_average  vote_count
 0     184.1031         9.000        1656
 1      90.5775         8.722       30538
 2      44.2900         8.688       23019
 3     188.8313         8.700        4929
 4      30.5158         8.572       13958
 5      38.6440         8.572         598
 6      26.0480         8.569       17506
 7      23.5013         8.600       10029
 8      32.6243         8.535       18392
 9      41.6990         8.531       35877
 10     17.1904         8.513        4593
 11    382.8024         8.510        1916
 12     27.2486         8.507       19313
 13     45.3962         8.499       26628
 14     36.4975         8.494       20712
 15     10.2466         8.500         354
 16     31.8224         8.483       30264
 17     28.1092         8.481       12606
 18     70.5674         8.478       39986
 19     25.4030         8.500        9676  ,
         id                                              title  \
 0       13                                       Forrest Gump
 1      769                                         GoodFellas
 2      346                                      Seven Samurai
 3    12477                             Grave of the Fireflies
 4      637                                  Life Is Beautiful
 5      550                                         Fight Club
 6    14537                                           Harakiri
 7      120  The Lord of the Rings: The Fellowship of the Ring
 8      598                                        City of God
 9    11216                                    Cinema Paradiso
 10     121              The Lord of the Rings: The Two Towers
 11     539                                             Psycho
 12     510                    One Flew Over the Cuckoo's Nest
 13   40096                                       A Dog's Will
 14  255709                                               Hope
 15  667257                                  Impossible Things
 16  324857                  Spider-Man: Into the Spider-Verse
 17    1891                            The Empire Strikes Back
 18    4935                               Howl's Moving Castle
 19  378064                          A Silent Voice: The Movie

                                              overview release_date  \
 0   A man with a low IQ has accomplished great thi...   1994-06-23
 1   The true story of Henry Hill, a half-Irish, ha...   1990-09-12
 2   A samurai answers a village's request for prot...   1954-04-26
 3   In the final months of World War II, 14-year-o...   1988-04-16
 4   A touching story of an Italian book seller of ...   1997-12-20
 5   A ticking-time-bomb insomniac and a slippery s...   1999-10-15
 6   Down-on-his-luck veteran Tsugumo Hanshirō ente...   1962-09-15
 7   Young hobbit Frodo Baggins, after inheriting a...   2001-12-18
 8   In the poverty-stricken favelas of Rio de Jane...   2002-08-30
 9   A filmmaker recalls his childhood, when he fel...   1988-11-17
 10  Frodo Baggins and the other members of the Fel...   2002-12-18
 11  When larcenous real estate clerk Marion Crane ...   1960-06-22
 12  A petty criminal fakes insanity to serve his s...   1975-11-19
 13  The lively João Grilo and the sly Chicó are po...   2000-09-15
 14  After 8-year-old So-won narrowly survives a br...   2013-10-02
 15  After the death of her abusive husband, Matild...   2021-06-17
 16  Struggling to find his place in the world whil...   2018-12-06
 17  The epic saga continues as Luke Skywalker, in ...   1980-05-20
 18  Sophie, a young milliner, is turned into an el...   2004-09-09
 19  Shouya Ishida starts bullying the new girl in ...   2016-09-17

     popularity  vote_average  vote_count
 0      28.6543         8.465       29821
 1      27.6023         8.454       14400
 2      12.7897         8.400        4244
 3       0.0119         8.444        6541
 4      14.0767         8.439       14013
 5      33.4766         8.438       32130
 6       8.2333         8.438        1218
 7      36.1880         8.434       27640
 8      11.1839         8.430        8201
 9      11.7544         8.428        4839
 10     28.7286         8.420       23956
 11     15.1681         8.400       11006
 12     12.0270         8.412       11476
 13      5.1292         8.408        1223
 14     11.6067         8.400         862
 15      4.5116         8.395         422
 16     23.3559         8.400       17280
 17     12.4043         8.400       18451
 18     23.2624         8.388       11109
 19     14.8592         8.400        4502  ,
          id                                  title  \
 0    770156  Lucy Shimmers and the Prince of Peace
 1    696374                      Gabriel's Inferno
 2       807                                  Se7en
 3       311            Once Upon a Time in America
 4   1218925     Chainsaw Man - The Movie: Reze Arc
 5    244786                               Whiplash
 6       423                            The Pianist
 7     27205                              Inception
 8     12493                           High and Low
 9   1439930            The Punisher: One Last Kill
 10   724089             Gabriel's Inferno: Part II
 11      274               The Silence of the Lambs
 12   761053            Gabriel's Inferno: Part III
 13      567                            Rear Window
 14   569094    Spider-Man: Across the Spider-Verse
 15  1058694                                Radical
 16       73                     American History X
 17      105                     Back to the Future
 18      128                      Princess Mononoke
 19  1184918                         The Wild Robot

                                              overview release_date  \
 0   Second chances start when a hardened criminal ...   2020-10-19
 1   An intriguing and sinful exploration of seduct...   2020-05-29
 2   Two homicide detectives are on a desperate hun...   1995-09-22
 3   A former Prohibition-era Jewish gangster retur...   1984-05-23
 4   In a brutal war between devils, hunters, and s...   2025-09-19
 5   Under the direction of a ruthless instructor, ...   2014-10-10
 6   The true story of pianist Władysław Szpilman's...   2002-09-17
 7   Cobb, a skilled thief who commits corporate es...   2010-07-15
 8   A Yokohama shoe executive faces a wrenching ch...   1963-03-01
 9   As Frank Castle searches for meaning beyond re...   2026-05-12
 10  Professor Gabriel Emerson finally learns the t...   2020-07-31
 11  Clarice Starling is a top student at the FBI's...   1991-02-14
 12  The final part of the film adaption of the ero...   2020-11-19
 13  A wheelchair-bound photographer spies on his n...   1954-08-01
 14  After reuniting with Gwen Stacy, Brooklyn’s fu...   2023-05-31
 15  In a Mexican border town plagued by neglect, c...   2023-10-19
 16  Derek Vineyard is paroled after serving 3 year...   1998-07-01
 17  Eighties teenager Marty McFly is accidentally ...   1985-07-03
 18  Ashitaka, a prince of the disappearing Emishi ...   1997-07-12
 19  After a shipwreck, an intelligent robot called...   2024-09-12

     popularity  vote_average  vote_count
 0       8.4860         8.384         363
 1       4.6139         8.383        2470
 2      27.0117         8.382       23137
 3      14.9581         8.400        6053
 4      26.2908         8.400         911
 5      25.0535         8.375       16658
 6      11.3324         8.400       10150
 7      32.9299         8.372       39344
 8       7.7832         8.400        1129
 9     193.0883         8.357        1562
 10      3.3739         8.349        1555
 11      4.6207         8.345       18022
 12      6.6516         8.340        1089
 13      8.6873         8.300        7176
 14     28.5496         8.300        8654
 15      4.5983         8.329         506
 16     10.8240         8.327       12599
 17     19.6975         8.300       21850
 18     16.8239         8.321        9017
 19     37.0869         8.314        6131  ,
          id                                 title  \
 0     10494                          Perfect Blue
 1      3782                                 Ikiru
 2       207                    Dead Poets Society
 3    533514          Violet Evergarden: The Movie
 4       101                Léon: The Professional
 5    644479                    Dedicated to my ex
 6     42269       We All Loved Each Other So Much
 7      1585                 It's a Wonderful Life
 8    620249                     The Legend of Hei
 9    820067  The Quintessential Quintuplets Movie
 10   372754              Dou kyu sei – Classmates
 11     3082                          Modern Times
 12      914                    The Great Dictator
 13      599                      Sunset Boulevard
 14      335          Once Upon a Time in the West
 15    77338                      The Intouchables
 16       28                        Apocalypse Now
 17  1317149                               I Swear
 18   652837         Josee, the Tiger and the Fish
 19  1139087                    Once Upon a Studio

                                              overview release_date  \
 0   Rising pop star Mima quits singing to pursue a...   1998-02-28
 1   Kanji Watanabe is a middle-aged man who has wo...   1952-10-09
 2   At an elite, old-fashioned boarding school in ...   1989-06-02
 3   As the world moves on from the war and technol...   2020-09-18
 4   Léon, the top hit man in New York, has earned ...   1994-09-14
 5   The film tells the story of Ariel, a 21-year-o...   2019-11-01
 6   Three partisans bound by a strong friendship r...   1974-12-21
 7   George Bailey has spent his entire life giving...   1946-12-20
 8   When cat spirit Luo Xiaohei's home is deforest...   2019-08-27
 9   When five lovely young girls who hate studying...   2022-05-20
 10  Rihito Sajo, an honor student with a perfect s...   2016-02-20
 11  A bumbling tramp desires to build a home with ...   1936-02-05
 12  Dictator Adenoid Hynkel tries to expand his em...   1940-10-15
 13  A hack screenwriter writes a screenplay for a ...   1950-08-10
 14  As the railroad builders advance unstoppably t...   1968-12-21
 15  A true story of two men who should never have ...   2011-11-02
 16  At the height of the Vietnam war, Captain Benj...   1979-05-19
 17  Diagnosed with Tourette Syndrome at 15, John D...   2025-09-22
 18  With dreams of diving abroad, Tsuneo gets a jo...   2020-12-25
 19  Created for Disney's 100th anniversary, the sh...   2023-09-24

     popularity  vote_average  vote_count
 0      12.3920         8.306        3207
 1       7.1540         8.302        1347
 2      15.4141         8.300       12629
 3       6.8052         8.297         515
 4      15.7655         8.300       16144
 5       3.6360         8.300         513
 6       3.8043         8.300         651
 7       8.2453         8.282        4913
 8      10.0342         8.281         473
 9       7.1128         8.280         444
 10      5.0941         8.300         441
 11      7.1349         8.279        4088
 12      6.9633         8.300        3707
 13      7.3854         8.300        2941
 14     11.5016         8.273        4909
 15     22.5182         8.271       18455
 16     12.8269         8.269        9114
 17     12.2621         8.265         342
 18      6.4153         8.268         601
 19      4.9892         8.300         433  ,
          id                                           title  \
 0    654299                       Out of the Clear Blue Sky
 1     92321                              Hotarubi no Mori e
 2     18491  Neon Genesis Evangelion: The End of Evangelion
 3       975                                  Paths of Glory
 4      8587                                   The Lion King
 5     92060                      Michael Jackson's Thriller
 6     15804                           A Brighter Summer Day
 7       901                                     City Lights
 8    637920                           Miracle in Cell No. 7
 9     29259                                         Le Trou
 10      603                                      The Matrix
 11  1356039                                   Counterattack
 12   630566                                          Clouds
 13    10376                              The Legend of 1900
 14      670                                          Oldboy
 15   299536                          Avengers: Infinity War
 16   299534                               Avengers: Endgame
 17   632632                                           Given
 18   504253                     I Want to Eat Your Pancreas
 19      857                             Saving Private Ryan

                                              overview release_date  \
 0   Returning to Earth as an imitator, the legenda...   2019-12-24
 1   One hot summer day a little girl gets lost in ...   2011-09-17
 2   SEELE orders an all-out attack on NERV, aiming...   1997-07-19
 3   A commanding officer defends three scapegoats ...   1957-10-25
 4   Young lion prince Simba, eager to one day beco...   1994-06-15
 5   A night at the movies turns terrifying when Mi...   1983-11-21
 6   A boy experiences first love, friendships and ...   1991-07-27
 7   A tramp falls in love with a beautiful blind f...   1931-02-06
 8   Separated from his daughter, a father with an ...   2019-10-10
 9   Four prison inmates have been hatching a plan ...   1960-03-18
 10  Set in the 22nd century, The Matrix tells the ...   1999-03-31
 11  When a hostage rescue mission creates a new en...   2025-02-27
 12  Young musician Zach Sobiech discovers his canc...   2020-10-09
 13  Musician Max Tooney goes to sell his prized Co...   1998-10-28
 14  With no clue how he came to be imprisoned, dru...   2003-11-21
 15  As the Avengers and their allies have continue...   2018-04-25
 16  After the devastating events of Avengers: Infi...   2019-04-24
 17  Haruki secretly had feelings for Akihiko for y...   2020-08-22
 18  After his classmate and crush is diagnosed wit...   2018-09-01
 19  As U.S. troops storm the beaches of Normandy, ...   1998-07-24

     popularity  vote_average  vote_count
 0       3.3842         8.263         384
 1       0.0095         8.257        1218
 2      10.2426         8.255        1859
 3       6.0486         8.300        3278
 4      27.6576         8.254       19717
 5       7.3098         8.300         768
 6       6.7667         8.253         391
 7       5.8976         8.252        2459
 8       8.1641         8.251        4566
 9       5.5827         8.251         575
 10     53.8159         8.247       27996
 11      8.2340         8.243         821
 12      1.9396         8.243        1054
 13      5.9810         8.242        2450
 14     12.1773         8.238        9884
 15     49.9642         8.237       32087
 16     32.3524         8.237       27819
 17      3.6476         8.227         420
 18      7.2763         8.227        1784
 19     16.8832         8.200       17278  ,
         id                                              title  \
 0       98                                          Gladiator
 1   572154           Rascal Does Not Dream of a Dreaming Girl
 2   490132                                         Green Book
 3   508965                                              Klaus
 4   447362                                     Life in a Year
 5   995133           The Boy, the Mole, the Fox and the Horse
 6    24188                                        Il Sorpasso
 7    16869                               Inglourious Basterds
 8   527641                                    Five Feet Apart
 9   110420                                      Wolf Children
 10  635302  Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...
 11   25237                                       Come and See
 12    1124                                       The Prestige
 13  315162                       Puss in Boots: The Last Wish
 14   16672                                 Woman in the Dunes
 15   37257                        Witness for the Prosecution
 16  265177                                              Mommy
 17      11                                          Star Wars
 18  283566             Evangelion: 3.0+1.0 Thrice Upon a Time
 19     694                                        The Shining

                                              overview release_date  \
 0   After the death of Emperor Marcus Aurelius, hi...   2000-05-04
 1   In Fujisawa, Sakuta Azusagawa is in his second...   2019-06-15
 2   Tony Lip, a bouncer in 1962, is hired to drive...   2018-11-16
 3   A selfish postman and a reclusive toymaker for...   2019-11-08
 4   A 17 year old finds out that his girlfriend is...   2020-11-27
 5   The unlikely friendship of a boy, a mole, a fo...   2022-12-25
 6   Roberto, a shy law student in Rome, meets Brun...   1962-12-05
 7   In Nazi-occupied France during World War II, a...   2009-08-02
 8   Seventeen-year-old Stella spends most of her t...   2019-03-14
 9   After her werewolf lover unexpectedly dies in ...   2012-07-21
 10  Tanjiro Kamado, joined with Inosuke Hashibira,...   2020-10-16
 11  The invasion of a village in Belarus by German...   1985-10-17
 12  A mysterious story of two magicians whose inte...   2006-10-19
 13  Puss in Boots discovers that his passion for a...   2022-12-07

In [11]:
df.to_csv('movies.csv', index=False) # now you can upload to kaggle

# use rapid api get data convert to csv and upload to kaggle